export default {
  'Large towel': false,
  'Hand towel': false,
  Washcloth: false,
  PJs: false,
  Underwear: false,
  'Socks (2 pair min)': false,
  'Comfy shoes': false,
  'Athletic shoes': false,
  Soap: false,
  Deodorant: false,
  Shampoo: false,
  'Toothbrush / toothpaste': false,
  'Comb / brush': false,
  Sunscreen: false,
  'Insect repellant': false,
  Lotion: false,
  'Medications (your leader needs to know)': false,
  Scriptures: false,
  Journal: false,
  Pen: false,
  'Water Bottle (to fill)': false,
  'Camera (if desired)': false,
  'Clothes (EFY standards)': false,
};
