export default {
  'Permission form': false,
  Pillow: false,
  'Sleeping Bag': false,
  'Sleeping Pad': false,
  'Blanket (optional)': false,
  Backpack: false,
  'Water Bottle (to fill)': false,
  Towel: false,
  PJs: false,
  "Clothes for 3 days (don't forget socks and underwear)": false,
  'Good Shoes': false,
  Deodorant: false,
  'Toothbrush / toothpaste': false,
  Sunscreen: false,
  'Insect repellant': false,
  'Medications (your leader needs to know)': false,
  'Scriptures (optional)': false,
  'Camera (if desired)': false,
};
