export default {
  'Permission form': false,
  'Medications (your leader needs to know!)': false,
  'Socks (7 or 8 pair)': false,
  'Shorts and/or pants': false,
  '2 or 3 T-shirts (no tank tops)': false,
  Underwear: false,
  'Shoes or Boots (completely closed, no Crocs or sandals)': false,
  'Water shoes (Aqua socks, etc.)': false,
  'Cap or Hat for sun protection': false,
  'Pajamas or sleeping clothes': false,
  'Sleeping Bag or 2 blankets and sheet': false,
  Pillow: false,
  'Sleeping pad': false,
  'Personal First Aid Kit': false,
  'Poncho or Rain jacket': false,
  'Towels and washcloth': false,
  Deodorant: false,
  'Soap and Shampoo': false,
  'Toothbrush and Toothpaste': false,
  'Comb, Brush, and Mirror': false,
  'Flashlight and extra batteries': false,
  'Pocket knife': false,
  'Insect repellent (non-aerosol)': false,
  'Swim suit (no cut-offs)': false,
  'Sun screen': false,
  'Water Bottle or Canteen and Cup': false,
  Scriptures: false,
  'Spiral Notebooks': false,
  'Pen or Pencil': false,
  'Spending Money': false,
};
